In [1]:
import pandas as pd
df_loan = pd.read_csv('loan_approval_dataset.csv')
df_loan.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [2]:
df_loan2=df_loan.copy()

In [3]:
df_loan2.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [6]:
df_loan2["loan_status"] = df_loan2["loan_status"].str.strip()
df_loan2["loan_status_encoded"] = df_loan2["loan_status"].map({"Rejected":0, "Approved":1})
df_loan2 = df_loan2.drop(columns=["loan_status"])
df_loan2["self_employed"] = df_loan2["self_employed"].str.strip()
df_loan2["self_employed_encoded"] = df_loan2["self_employed"].map({"No":0, "Yes":1})
df_loan2 = df_loan2.drop(columns=["self_employed"])
df_loan2["education"] = df_loan2["education"].str.strip()
df_loan2["education_encoded"] = df_loan2["education"].map({"Graduate":0, "Not Graduate":1})
df_loan2 = df_loan2.drop(columns=["education"])

In [7]:
df_loan2 = df_loan2.drop(columns=["loan_id"])

In [5]:
df_loan2.columns = df_loan2.columns.str.strip()
df_loan2["loan_to_income"] = df_loan2["loan_amount"] / (df_loan2["income_annum"]+1e-6)
df_loan2["total_assets"] = (df_loan2["residential_assets_value"] +
                            df_loan2["commercial_assets_value"] +
                            df_loan2["luxury_assets_value"] +
                            df_loan2["bank_asset_value"])
df_loan2["assets_to_loan"] = df_loan2["total_assets"] / (df_loan2["loan_amount"]+1e-6)

In [8]:
import mlflow
import mlflow.sklearn

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

X = df_loan2.drop(columns=["loan_status_encoded"])
y = df_loan2["loan_status_encoded"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

with mlflow.start_run():

    model = DecisionTreeClassifier(
        max_depth=7,
        min_samples_split=5,
        min_samples_leaf=10,
        random_state=42,
        class_weight="balanced"
    )

    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    print("Accuracy:", acc)
    print("Precision:", prec)
    print("Recall:", rec)
    print("F1-score:", f1)

    # تسجيل ال parameters
    mlflow.log_param("max_depth", 7)
    mlflow.log_param("min_samples_split", 5)
    mlflow.log_param("min_samples_leaf", 10)

    # تسجيل ال metrics
    mlflow.log_metric("accuracy", acc)
    mlflow.log_metric("precision", prec)
    mlflow.log_metric("recall", rec)
    mlflow.log_metric("f1_score", f1)

    # حفظ الموديل
    mlflow.sklearn.log_model(model, "decision_tree_model")

2026/03/12 02:06:17 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

2026/03/12 02:06:17 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.

Accuracy: 1.0
Precision: 1.0
Recall: 1.0
F1-score: 1.0

2026/03/12 02:06:17 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

In [ ]:
import mlflow
# السطر ده هو الأهم: بيخلي الـ Notebook يكتب في قاعدة البيانات اللي في الصورة
mlflow.set_tracking_uri("sqlite:///mlflow.db")

# ده بيخليك تلاقي نتائجك تحت اسم واضح بدل "Default"
mlflow.set_experiment("Loan_Prediction_Exp")

<Experiment: artifact_location='file:c:/Users/Mahmoud/Desktop/VS CODE/loan_approval/mlruns/1', creation_time=1773271853410, experiment_id='1', last_update_time=1773271853410, lifecycle_stage='active', name='Loan_Prediction_Exp', tags={}, workspace='default'>

In [ ]:
%pip install mlflow

Collecting mlflowNote: you may need to restart the kernel to use updated packages.

  Using cached mlflow-3.10.1-py3-none-any.whl.metadata (31 kB)
Collecting mlflow-skinny==3.10.1 (from mlflow)
  Using cached mlflow_skinny-3.10.1-py3-none-any.whl.metadata (32 kB)
Collecting mlflow-tracing==3.10.1 (from mlflow)
  Using cached mlflow_tracing-3.10.1-py3-none-any.whl.metadata (19 kB)
Collecting Flask-CORS<7 (from mlflow)
  Using cached flask_cors-6.0.2-py3-none-any.whl.metadata (5.3 kB)
Requirement already satisfied: Flask<4 in c:\users\mahmoud\anaconda3\lib\site-packages (from mlflow) (3.1.0)
Requirement already satisfied: alembic!=1.10.0,<2 in c:\users\mahmoud\anaconda3\lib\site-packages (from mlflow) (1.16.5)
Requirement already satisfied: cryptography<47,>=43.0.0 in c:\users\mahmoud\anaconda3\lib\site-packages (from mlflow) (44.0.1)
Collecting docker<8,>=4.0.0 (from mlflow)
  Using cached docker-7.1.0-py3-none-any.whl.metadata (3.8 kB)
Collecting graphene<4 (from mlflow)
  Using cached graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)
Collecting huey<3,>=2.5.4 (from mlflow)
  Using cached huey-2.6.0-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: matplotlib<4 in c:\users\mahmoud\anaconda3\lib\site-packages (from mlflow) (3.10.0)
Requirement already satisfied: numpy<3 in c:\users\mahmoud\anaconda3\lib\site-packages (from mlflow) (2.1.3)
Requirement already satisfied: pandas<3 in c:\users\mahmoud\anaconda3\lib\site-packages (from mlflow) (2.2.3)
Requirement already satisfied: pyarrow<24,>=4.0.0 in c:\users\mahmoud\anaconda3\lib\site-packages (from mlflow) (19.0.0)
Requirement already satisfied: scikit-learn<2 in c:\users\mahmoud\anaconda3\lib\site-packages (from mlflow) (1.6.1)
Requirement already satisfied: scipy<2 in c:\users\mahmoud\anaconda3\lib\site-packages (from mlflow) (1.15.3)
Collecting skops<1 (from mlflow)
  Using cached skops-0.13.0-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in c:\users\mahmoud\anaconda3\lib\site-packages (from mlflow) (2.0.39)
Collecting waitress<4 (from mlflow)
  Using cached waitress-3.0.2-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: cachetools<8,>=5.0.0 in c:\users\mahmoud\anaconda3\lib\site-packages (from mlflow-skinny==3.10.1->mlflow) (5.5.1)
Requirement already satisfied: click<9,>=7.0 in c:\users\mahmoud\anaconda3\lib\site-packages (from mlflow-skinny==3.10.1->mlflow) (8.1.8)
Requirement already satisfied: cloudpickle<4 in c:\users\mahmoud\anaconda3\lib\site-packages (from mlflow-skinny==3.10.1->mlflow) (3.0.0)
Collecting databricks-sdk<1,>=0.20.0 (from mlflow-skinny==3.10.1->mlflow)
  Using cached databricks_sdk-0.98.0-py3-none-any.whl.metadata (40 kB)
Collecting fastapi<1 (from mlflow-skinny==3.10.1->mlflow)
  Using cached fastapi-0.135.1-py3-none-any.whl.metadata (30 kB)
Requirement already satisfied: gitpython<4,>=3.1.9 in c:\users\mahmoud\anaconda3\lib\site-packages (from mlflow-skinny==3.10.1->mlflow) (3.1.43)
Requirement already satisfied: importlib_metadata!=4.7.0,<9,>=3.7.0 in c:\users\mahmoud\anaconda3\lib\site-packages (from mlflow-skinny==3.10.1->mlflow) (8.5.0)
Collecting opentelemetry-api<3,>=1.9.0 (from mlflow-skinny==3.10.1->mlflow)
  Using cached opentelemetry_api-1.40.0-py3-none-any.whl.metadata (1.5 kB)
Collecting opentelemetry-proto<3,>=1.9.0 (from mlflow-skinny==3.10.1->mlflow)
  Using cached opentelemetry_proto-1.40.0-py3-none-any.whl.metadata (2.4 kB)
Collecting opentelemetry-sdk<3,>=1.9.0 (from mlflow-skinny==3.10.1->mlflow)
  Using cached opentelemetry_sdk-1.40.0-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: packaging<27 in c:\users\mahmoud\anaconda3\lib\site-packages (from mlflow-skinny==3.10.1->mlflow) (24.2)
Requirement already satisfied: protobuf<7,>=3.12.0 in c:\users\mahmoud\anaconda3\lib\site-packages (from mlflow-skinny==3.10.1->mlflow) (5.29.3)
Requirement already satisfied: pydantic<3,>=2.0.0 in c:\users\mahmoud\anaconda3\lib\site-packages (from mlflow-skinny==3.10.1->mlflow) (2.10.3)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in c:\users\mahmoud\anaconda3\lib\site-packages (from mlflow-skinny==3.10.1->mlflow) (1.1.0)
Requirement already satisfied: pyyaml<7,>=5.1 in c:\users\mahmoud\anaconda3\lib\site-packages (from mlflow-skinny==3.10.1->mlflow) (6.0.2)
Requirement already satisfied: requests<3,>=2.17.3 in c:\users\mahmoud\anaconda3\lib\site-packages (from mlflow-skinny==3.10.1->mlflow) (2.32.3)
Collecting sqlparse<1,>=0.4.0 (from mlflow-skinny==3.10.1->mlflow)
  Using cached sqlparse-0.5.5-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in c:\users\mahmoud\anaconda3\lib\site-packages (from mlflow-skinny==3.10.1->mlflow) (4.12.2)
Collecting uvicorn<1 (from mlflow-skinny==3.10.1->mlflow)
  Using cached uvicorn-0.41.0-py3-none-any.whl.metadata (6.7 kB)
Requirement already satisfied: Mako in c:\users\mahmoud\anaconda3\lib\site-packages (from alembic!=1.10.0,<2->mlflow) (1.3.10)
Requirement already satisfied: colorama in c:\users\mahmoud\anaconda3\lib\site-packages (from click<9,>=7.0->mlflow-skinny==3.10.1->mlflow) (0.4.6)
Requirement already satisfied: cffi>=1.12 in c:\users\mahmoud\anaconda3\lib\site-packages (from cryptography<47,>=43.0.0->mlflow) (1.17.1)
Collecting google-auth~=2.0 (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.10.1->mlflow)
  Using cached google_auth-2.49.0-py3-none-any.whl.metadata (6.2 kB)
Collecting protobuf<7,>=3.12.0 (from mlflow-skinny==3.10.1->mlflow)
  Using cached protobuf-6.33.5-cp310-abi3-win_amd64.whl.metadata (593 bytes)
Requirement already satisfied: pywin32>=304 in c:\users\mahmoud\anaconda3\lib\site-packages (from docker<8,>=4.0.0->mlflow) (308)
Requirement already satisfied: urllib3>=1.26.0 in c:\users\mahmoud\anaconda3\lib\site-packages (from docker<8,>=4.0.0->mlflow) (2.3.0)
Collecting starlette>=0.46.0 (from fastapi<1->mlflow-skinny==3.10.1->mlflow)
  Using cached starlette-0.52.1-py3-none-any.whl.metadata (6.3 kB)
Collecting typing-inspection>=0.4.2 (from fastapi<1->mlflow-skinny==3.10.1->mlflow)
  Using cached typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Collecting annotated-doc>=0.0.2 (from fastapi<1->mlflow-skinny==3.10.1->mlflow)
  Using cached annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: Werkzeug>=3.1 in c:\users\mahmoud\anaconda3\lib\site-packages (from Flask<4->mlflow) (3.1.3)
Requirement already satisfied: Jinja2>=3.1.2 in c:\users\mahmoud\anaconda3\lib\site-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: itsdangerous>=2.2 in c:\users\mahmoud\anaconda3\lib\site-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: blinker>=1.9 in c:\users\mahmoud\anaconda3\lib\site-packages (from Flask<4->mlflow) (1.9.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\mahmoud\anaconda3\lib\site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.10.1->mlflow) (4.0.7)
Requirement already satisfied: smmap<5,>=3.0.1 in c:\users\mahmoud\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.10.1->mlflow) (4.0.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\mahmoud\anaconda3\lib\site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.10.1->mlflow) (0.2.8)
Collecting rsa<5,>=3.1.4 (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.10.1->mlflow)
  Using cached rsa-4.9.1-py3-none-any.whl.metadata (5.6 kB)
Collecting graphql-core<3.3,>=3.1 (from graphene<4->mlflow)
  Using cached graphql_core-3.2.8-py3-none-any.whl.metadata (11 kB)
Collecting graphql-relay<3.3,>=3.1 (from graphene<4->mlflow)
  Using cached graphql_relay-3.2.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in c:\users\mahmoud\anaconda3\lib\site-packages (from graphene<4->mlflow) (2.9.0.post0)
Requirement already satisfied: zipp>=3.20 in c:\users\mahmoud\anaconda3\lib\site-packages (from importlib_metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==3.10.1->mlflow) (3.21.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\mahmoud\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\mahmoud\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\mahmoud\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\mahmoud\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (1.4.8)
Requirement already satisfied: pillow>=8 in c:\users\mahmoud\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\mahmoud\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (3.2.0)
Collecting opentelemetry-semantic-conventions==0.61b0 (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.10.1->mlflow)
  Using cached opentelemetry_semantic_conventions-0.61b0-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: pytz>=2020.1 in c:\users\mahmoud\anaconda3\lib\site-packages (from pandas<3->mlflow) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\mahmoud\anaconda3\lib\site-packages (from pandas<3->mlflow) (2025.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\mahmoud\anaconda3\lib\site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.10.1->mlflow) (0.6.0)
Requirement already satisfied: pydantic-core==2.27.1 in c:\users\mahmoud\anaconda3\lib\site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.10.1->mlflow) (2.27.1)
Requirement already satisfied: six>=1.5 in c:\users\mahmoud\anaconda3\lib\site-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\mahmoud\anaconda3\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.10.1->mlflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\mahmoud\anaconda3\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.10.1->mlflow) (3.7)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\mahmoud\anaconda3\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.10.1->mlflow) (2025.10.5)
Requirement already satisfied: pyasn1>=0.1.3 in c:\users\mahmoud\anaconda3\lib\site-packages (from rsa<5,>=3.1.4->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.10.1->mlflow) (0.4.8)
Requirement already satisfied: joblib>=1.2.0 in c:\users\mahmoud\anaconda3\lib\site-packages (from scikit-learn<2->mlflow) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\mahmoud\anaconda3\lib\site-packages (from scikit-learn<2->mlflow) (3.5.0)
Collecting prettytable>=3.9 (from skops<1->mlflow)
  Using cached prettytable-3.17.0-py3-none-any.whl.metadata (34 kB)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\mahmoud\anaconda3\lib\site-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.1.1)
Requirement already satisfied: h11>=0.8 in c:\users\mahmoud\anaconda3\lib\site-packages (from uvicorn<1->mlflow-skinny==3.10.1->mlflow) (0.16.0)
Requirement already satisfied: pycparser in c:\users\mahmoud\anaconda3\lib\site-packages (from cffi>=1.12->cryptography<47,>=43.0.0->mlflow) (2.21)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\mahmoud\anaconda3\lib\site-packages (from Jinja2>=3.1.2->Flask<4->mlflow) (3.0.2)
Requirement already satisfied: wcwidth in c:\users\mahmoud\anaconda3\lib\site-packages (from prettytable>=3.9->skops<1->mlflow) (0.2.5)
Requirement already satisfied: anyio<5,>=3.6.2 in c:\users\mahmoud\anaconda3\lib\site-packages (from starlette>=0.46.0->fastapi<1->mlflow-skinny==3.10.1->mlflow) (4.7.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\mahmoud\anaconda3\lib\site-packages (from anyio<5,>=3.6.2->starlette>=0.46.0->fastapi<1->mlflow-skinny==3.10.1->mlflow) (1.3.0)
Using cached mlflow-3.10.1-py3-none-any.whl (10.2 MB)
Using cached mlflow_skinny-3.10.1-py3-none-any.whl (3.0 MB)
Using cached mlflow_tracing-3.10.1-py3-none-any.whl (1.5 MB)
Using cached databricks_sdk-0.98.0-py3-none-any.whl (828 kB)
Using cached docker-7.1.0-py3-none-any.whl (147 kB)
Using cached fastapi-0.135.1-py3-none-any.whl (116 kB)
Using cached flask_cors-6.0.2-py3-none-any.whl (13 kB)
Using cached google_auth-2.49.0-py3-none-any.whl (240 kB)
Using cached graphene-3.4.3-py2.py3-none-any.whl (114 kB)
Using cached graphql_core-3.2.8-py3-none-any.whl (207 kB)
Using cached graphql_relay-3.2.0-py3-none-any.whl (16 kB)
Using cached huey-2.6.0-py3-none-any.whl (76 kB)
Using cached opentelemetry_api-1.40.0-py3-none-any.whl (68 kB)
Using cached opentelemetry_proto-1.40.0-py3-none-any.whl (72 kB)
Using cached opentelemetry_sdk-1.40.0-py3-none-any.whl (141 kB)
Using cached opentelemetry_semantic_conventions-0.61b0-py3-none-any.whl (231 kB)
Using cached protobuf-6.33.5-cp310-abi3-win_amd64.whl (437 kB)
Using cached rsa-4.9.1-py3-none-any.whl (34 kB)
Using cached skops-0.13.0-py3-none-any.whl (131 kB)
Using cached sqlparse-0.5.5-py3-none-any.whl (46 kB)
Using cached uvicorn-0.41.0-py3-none-any.whl (68 kB)
Using cached waitress-3.0.2-py3-none-any.whl (56 kB)
Using cached annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Using cached prettytable-3.17.0-py3-none-any.whl (34 kB)
Using cached starlette-0.52.1-py3-none-any.whl (74 kB)
Using cached typing_inspection-0.4.2-py3-none-any.whl (14 kB)
Installing collected packages: huey, waitress, typing-inspection, sqlparse, rsa, protobuf, prettytable, graphql-core, annotated-doc, uvicorn, starlette, opentelemetry-proto, opentelemetry-api, graphql-relay, docker, skops, opentelemetry-semantic-conventions, graphene, google-auth, Flask-CORS, fastapi, opentelemetry-sdk, databricks-sdk, mlflow-tracing, mlflow-skinny, mlflow

   ----------------------------------------  0/26 [huey]
   ----------------------------------------  0/26 [huey]
   ----------------------------------------  0/26 [huey]
   ----------------------------------------  0/26 [huey]
   ----------------------------------------  0/26 [huey]
   - --------------------------------------  1/26 [waitress]
   - --------------------------------------  1/26 [waitress]
   ---- -----------------------------------  3/26 [sqlparse]
   ---- -----------------------------------  3/26 [sqlparse]
   ---- -----------------------------------  3/26 [sqlparse]
   ------ ---------------------------------  4/26 [rsa]
  Attempting uninstall: protobuf
   ------ ---------------------------------  4/26 [rsa]
    Found existing installation: protobuf 5.29.3
   ------ ---------------------------------  4/26 [rsa]
   ------- --------------------------------  5/26 [protobuf]
    Uninstalling protobuf-5.29.3:
   ------- --------------------------------  5/26 [protobuf]
      Successfully uninstalled protobuf-5.29.3
   ------- --------------------------------  5/26 [protobuf]
   ------- --------------------------------  5/26 [protobuf]
   ------- --------------------------------  5/26 [protobuf]
   ------- --------------------------------  5/26 [protobuf]
   ------- --------------------------------  5/26 [protobuf]
   ------- --------------------------------  5/26 [protobuf]
   ------- --------------------------------  5/26 [protobuf]
   ------- --------------------------------  5/26 [protobuf]
   --------- ------------------------------  6/26 [prettytable]
   ---------- -----------------------------  7/26 [graphql-core]
   ---------- -----------------------------  7/26 [graphql-core]
   ---------- -----------------------------  7/26 [graphql-core]
   ---------- -----------------------------  7/26 [graphql-core]
   ---------- -----------------------------  7/26 [graphql-core]
   ---------- -----------------------------  7/26 [graphql-core]
   ---------- -----------------------------  7/26 [graphql-core]
   ---------- -----------------------------  7/26 [graphql-core]
   ---------- -----------------------------  7/26 [graphql-core]
   ---------- -----------------------------  7/26 [graphql-core]
   ---------- -----------------------------  7/26 [graphql-core]
   ---------- -----------------------------  7/26 [graphql-core]
   ---------- -----------------------------  7/26 [graphql-core]
   ---------- -----------------------------  7/26 [graphql-core]
   ------------- --------------------------  9/26 [uvicorn]
   ------------- --------------------------  9/26 [uvicorn]
   ------------- --------------------------  9/26 [uvicorn]
   ------------- --------------------------  9/26 [uvicorn]
   ------------- --------------------------  9/26 [uvicorn]
   --------------- ------------------------ 10/26 [starlette]
   --------------- ------------------------ 10/26 [starlette]
   ---------------- ----------------------- 11/26 [opentelemetry-proto]
   ---------------- ----------------------- 11/26 [opentelemetry-proto]
   ------------------ --------------------- 12/26 [opentelemetry-api]
   ------------------ --------------------- 12/26 [opentelemetry-api]
   -------------------- ------------------- 13/26 [graphql-relay]
   --------------------- ------------------ 14/26 [docker]
   --------------------- ------------------ 14/26 [docker]
   --------------------- ------------------ 14/26 [docker]
   --------------------- ------------------ 14/26 [docker]
   --------------------- ------------------ 14/26 [docker]
   ----------------------- ---------------- 15/26 [skops]
   ----------------------- ---------------- 15/26 [skops]
   ----------------------- ---------------- 15/26 [skops]
   ----------------------- ---------------- 15/26 [skops]
   -------------------- ------------ 16/26 [opentelemetry-semantic-conventions]
   -------------------- ------------ 16/26 [opentelemetry-semantic-conventions]
   -------------------- ------------ 16/26 [opentelemetry-semantic-conventions]
   -------------------- ------------ 16/26 [opentelemetry-semantic-conventions]
   -------------------- ------------ 16/26 [opentelemetry-semantic-conventions]
   -------------------- ------------ 16/26 [opentelemetry-semantic-conventions]
   -------------------- ------------ 16/26 [opentelemetry-semantic-conventions]
   -------------------- ------------ 16/26 [opentelemetry-semantic-conventions]
   -------------------------- ------------- 17/26 [graphene]
   -------------------------- ------------- 17/26 [graphene]
   -------------------------- ------------- 17/26 [graphene]
   -------------------------- ------------- 17/26 [graphene]
   -------------------------- ------------- 17/26 [graphene]
   -------------------------- ------------- 17/26 [graphene]
   --------------------------- ------------ 18/26 [google-auth]
   --------------------------- ------------ 18/26 [google-auth]
   --------------------------- ------------ 18/26 [google-auth]
   --------------------------- ------------ 18/26 [google-auth]
   --------------------------- ------------ 18/26 [google-auth]
   ----------------------------- ---------- 19/26 [Flask-CORS]
   ------------------------------ --------- 20/26 [fastapi]
   ------------------------------ --------- 20/26 [fastapi]
   ------------------------------ --------- 20/26 [fastapi]
   ------------------------------ --------- 20/26 [fastapi]
   -------------------------------- ------- 21/26 [opentelemetry-sdk]
   -------------------------------- ------- 21/26 [opentelemetry-sdk]
   -------------------------------- ------- 21/26 [opentelemetry-sdk]
   -------------------------------- ------- 21/26 [opentelemetry-sdk]
   -------------------------------- ------- 21/26 [opentelemetry-sdk]
   --------------------------------- ------ 22/26 [databricks-sdk]
   --------------------------------- ------ 22/26 [databricks-sdk]
   --------------------------------- ------ 22/26 [databricks-sdk]
   --------------------------------- ------ 22/26 [databricks-sdk]
   --------------------------------- ------ 22/26 [databricks-sdk]

In [ ]:
import mlflow
import os

# 1. تحديد مسار قاعدة البيانات في الفولدر الحالي
db_path = os.path.abspath("mlflow.db")
mlflow.set_tracking_uri(f"sqlite:///{db_path}")

# 2. بدء تسجيل تجربة جديدة
mlflow.set_experiment("Final_Test")

with mlflow.start_run():
    mlflow.log_metric("accuracy", 0.95)
    mlflow.log_param("model_type", "DecisionTree")
    print("Done! Data sent to:", db_path)

2026/03/12 01:35:56 INFO mlflow.tracking.fluent: Experiment with name 'Final_Test' does not exist. Creating a new experiment.

Done! Data sent to: c:\Users\Mahmoud\Desktop\VS CODE\loan_approval\mlflow.db